name: Deploy StoryBook

on: 
  push:
    branches:
    - master

jobs: 
  build-and-deploy: 
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

        within:
          node-version: 16
    
      - name: Install dependencies
        run: npm ci

      - name: Build storybook
        run: npm run build-storybook

      - name: Deploy StoryBook
        run: npm run deploy-storybook -- --ci --existing-output-dir#storybook-static

        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}